dependencies:
  # These are in common between econ and math
  - conda-forge::pandas=2.0.0
  - conda-forge::xlsxwriter=3.0.9
  - conda-forge::sympy=1.11.1
  - conda-forge::scipy=1.10.1

  # These are unique to econ
  - conda-forge::squarify=0.4.3
  - conda-forge::openpyxl=3.1.1
  - conda-forge::requests=2.28.2
  - conda-forge::psycopg=3.1.11
  - conda-forge::cmasher=1.6.3
  - conda-forge::quantecon=0.5.2
  - conda-forge::scikit-learn=1.2.2
  - conda-forge::statsmodels=0.13.5
  - conda-forge::wbgapi=1.0.12
