name: Build and push Docker images

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

env:
  CACHE_TO_DEST: /tmp/.buildx-cache-new
  CACHE_FROM_SRC: /tmp/.buildx-cache

jobs:
  build-and-push-docker-images:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - dockerfile: src/Dockerfile.common.dev
            containerName: conda-econ-devcontainer
            containerTag: 1.0.0
            username: econ
            environmentName: econ
            environmentConfigPath: src/econ/environment.econ.yml
            additionalFilesToWatch: ""
          - dockerfile: src/Dockerfile.common.dev
            containerName: conda-math-devcontainer
            containerTag: 1.0.0
            username: math
            environmentName: math
            environmentConfigPath: src/math/environment.math.yml
            additionalFilesToWatch: ""
          - dockerfile: src/Dockerfile.common.dev
            containerName: conda-music-devcontainer
            containerTag: 1.0.0
            username: music
            environmentName: music
            environmentConfigPath: src/music/environment.music.yml
            additionalFilesToWatch: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v25
        with:
          files: |
            ${{ matrix.images.dockerfile }}
            ${{ matrix.images.environmentConfigPath }}
            ${{ matrix.images.additionalFilesToWatch }}

      - name: Declare run state
        run: |
          if [ ${{ steps.changed-files.outputs.any_modified }} == true ];
          then
            echo "Docker build will carry out as expected."
          else
            echo "Docker build is cancelled as none of the watched files changed."
          fi

      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_modified == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.images.containerName }}:${{ matrix.images.containerTag }}
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: docker/build-push-action@v2
        id: docker-build
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.images.containerName }}:${{ matrix.images.containerTag }}
          file: ${{ matrix.images.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=local,src=${{ env.CACHE_FROM_SRC }}
          cache-to: type=local,mode=max,dest=${{ env.CACHE_TO_DEST }}
          build-args: |
            ROOT_PASS=${{ secrets.DOCKER_IMAGE_ROOT_PASS }}
            USERNAME=${{ matrix.images.username }}
            ENVIRONMENT_NAME=${{ matrix.images.environmentName }}
            ENVIRONMENT_CONFIG=${{ matrix.images.environmentConfigPath }}

      - name: Image digest
        if: steps.changed-files.outputs.any_modified == 'true'
        run: echo ${{ steps.docker-build.outputs.digest }}

      - name: Move cache
        # if: steps.changed-files.outputs.any_modified == 'true'
        run: |
          rm -rf ${{ env.CACHE_FROM_SRC }}
          if [ -d ${{ env.CACHE_FROM_SRC }} ];
          then
            mv ${{ env.CACHE_TO_DEST }} ${{ env.CACHE_FROM_SRC }}
          fi
